### ISSUE TITLE
This library is amazing but...

### ISSUE THREAD

**Issue by XVincentX** [liguori/EasyDataFile#1]
...where is the implementation?

**Comment by liguori** [comment]
Hello Vincenzo, my first implementation will come soon (in this month). I hope you will contribute to it.

**Comment by XVincentX** [comment]
Looking forward, then.

**Comment by XVincentX** [comment]
I think this issue can now be closed. With 10 months of delay.

**Comment by XVincentX** [comment]
> Mi puzzano le palle.
