### ISSUE TITLE
Set a CI

### ISSUE THREAD

**Issue by XVincentX** [liguori/EasyDataFile#2]
Since I do not trust your test, please do set a [CI](https://appveyor.com) system for the project.

**Comment by liguori** [comment]
In minutes it will be done. I suppose you are using a MAC computer....ehehhehehe

**Comment by XVincentX** [comment]
You’re correct about my computer.

For what’s worth, last time you said “minutes” we waited for 7 months.

**Comment by liguori** [comment]
AppVeyor CI system has been added to the project. I hope you will enjoy it in the future. ;)
